### ISSUE TITLE
High level roadmap for v0.0.1

### ISSUE THREAD

**Issue by mlieberman85** [kusaridev/skootrs#62]
- [x] create projects
- [x] #64
- [x] fetch metadata regarding projects
- [x] fetch outputs of projects like SBOMs, SLSA, etc.
- [x] adopt existing projects into a local cache, i.e. allow Alice’s Skootrs to become aware of projects Bob’s Skootrs created assuming Alice has at least read access - Almost done
- [x] #65
- [x] #66

**Comment by mlieberman85** [comment]
Finished!
